### ISSUE TITLE
HexSeq shortkeys (d & h)

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#13]
Dear Christian,

I very much enjoy using shortkeys 'l' and 'r'. They're very useful. I would like to ask you to consider the implementation of two more shortcuts: 'd' (double) and 'h' (half).

Operation of 'd': it duplicates the length of a sequence by adding 0s after every step.
Operation of 'h': it halves the length of a sequence by removing every second step.

Example 1: 
```
Original bin:      1011001 (Hex: B2)
Then pressing 'd': 10001010000010 (Hex: 8A08)
Then pressing 'h': 1011001 (Hex: B2)
```

Example 2:
```
Original bin:      10101000101011 (Hex: A8AC)
Then pressing 'h': 1110111 (Hex: EE)
Then pressing 'd': 10101000101010 (Hex: A8A8)
```

Please note that in the second example some of the removed steps couldn't been recovered. Hence the start string and the final string are different. (See the last digit.)

I think it would be a fun and useful addition but I wouldn't claim it to be crucial. 

Cheers, Andras

**Comment by firolightfog** [comment]
I've just realized that 'd' is already in use. :)
Anyway he concept is clear I hope.

**Comment by docb** [comment]
hi Andras,
yes i thought already about something similar. but in a sense by halving or doubling speed. however i stopped this because doubling speed would only give an exact result if there are fitting zeros and the hexstring has an even number of chars and halving speed would only give an exact result if there is enough place.
so your press 'd' would be halving speed and if the results don't have to be exact then bits are lost if the hex string is > 8.
would be ok for me because a simple use case i would have will work: running a sequence with e.g. bpm 80 and then if want 1/32 notes i would halving the speed and clock with 160bpm.
ok and then i could revert it by doubling speed and lose the "1/32 notes".
And a length 5 would go to length 3. May be fair enough.
so now only the command chars are open.
v double speed, w half speed
or n double speed, m double speed.
best regards, christian

**Comment by firolightfog** [comment]
The idea to feed various clock signals to the 12 tracks of HexSeq is an elegant solution. You could do it without a GUI change by a **polyphonic clock input**. I see (and use) less sophisticated implementation of this multi-clock idea in other [sequencers](https://library.vcvrack.com/Sha-Bang-Modules/StochSeq4).

But I agree with you on simplicity and somehow prefer shortkeys. I'm a bit worried though for using **four** valuable letters for this feature. 

Please keep this proposal on your potential enhancement list but I'm **backing down my proposal** and suggesting you to **wait** for more feedback from other users. I also need to re-think about what's the most beneficial for my tunes.

Regards, Andras

**Comment by docb** [comment]
hi Andras, i meant either v,w or n,m. to be decided ...
best regards,
christian

**Comment by firolightfog** [comment]
Ah, sorry my bad. My choice is v & w.

**Comment by docb** [comment]
@firolightfog 2.1.4 the h key does half the speed. i.e. doubles the length. this i have done because e.g if an euclidean rhythm is generated via menu one may want to have the half speed of it. As the double speed operation would remove information in general and because it is easy to do by hand i have not implemented it.
If its ok for you i would close this issue.

**Comment by firolightfog** [comment]
H works nicely.
