### ISSUE TITLE
Question on Fla behaviour 

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#18]
Hallo Christian,

I was about to use Fla for some simple SUM function but the result was surprizing. Have I missed something in the manual (as I usually do)?

*Blue lines show the result of Fla, Submarine AO-101, Bogaudio Sums.*
<img width="389" alt="image" src="https://user-images.githubusercontent.com/34127628/151603249-f6b43c88-7246-4617-a894-b03716849805.png">

Best regards, Andras

**Comment by docb** [comment]
hi Andras,
FLA and FLL  normally completely destroy "normal audio" because integer arithmetic is applied to the signal not floating point. the origin of these modules is here:
https://www.youtube.com/watch?v=GtQdIYUtAHg (with 8-bit audio)

this is what i have done as demo some times ago. normally i feed the system with an extremely slow ramp, which
functions as the t variable in these small c programs. then the ramp is modulated with bitlogic and bit arithmetic producing  a broad spectrum of waves (non-band-limited).

![digi](https://user-images.githubusercontent.com/1134412/151607062-7c930dca-c99d-4f0e-b3d5-6f0fe8b00b49.png)

[digi001.txt](https://github.com/docb/dbRackModules/files/7961475/digi001.txt)
(rename digi001.txt to digi001.vcvs)

best regards,
christian
