### ISSUE TITLE
PAD2 enhancements - more CV control plus slew

### ISSUE THREAD

**Issue by DaveBenham** [docb/dbRackModules#20]
I am loving the sounds and design of PAD2, and it is spawning lots of ideas:

The Generate button that randomly creates partial amplitude profiles is begging for a trigger CV input to go with it.

And it would be great if there was an option for slew (knob and CV input) during profile transitions, expressed as seconds to morph from one profile to the next.

I think there should be 3 polyphonic CV inputs to cover the 48 partial amplitudes. There should be an option (control or context menu) to control whether the input voltages are sampled continuously, or by trigger. To keep things simple, you could ignore all partial inputs if the first input (2-17) is empty. If the first input is patched, then any missing channel(s) would default to 0.

I think less important, but still potentially useful would be 3 polyphonic outputs for the instantaneous partial values (reflecting any slew or morph state)

I envision the following rules for how the various inputs would interact:

If 1st partial input is empty, then:
 - 2nd and 3rd partial inputs are ignored
 - generate button (and new trigger input) randomly assign partial values following current method
 - time to morph from old profile to new is set by slew

If 1st partial input is not empty, then:
 - any unpatched partial channels default to 0
 - method control is ignored
 - If input mode is sample:
     - generate button/trigger samples inputs to assign partial values
     - time to morph from old profile to new is set by slew
 - If input mode is continuous:
     - partial values continuously updated by input values
     - generate button/input and slew knob/input are ignored

**Comment by docb** [comment]
When introducing the 3 CV inputs which is OK for me now, as it seems to be computationally feasible, i think the game changes a bit because then a lot can be done outside the module. 

My first thought was: does a module exist which can morph a polyphonic input based on a trigger as described above? 
May be i could take e.g. the RndH or another sample and hold and the slew limiter form bogaudio. 

Second: Is there still a need for the random generator?
The Faders module would also be capable of (by introducing these random methods in the menu for pressing Ctrl R).
And the other question arises: The Faders module could have this TRANSIT functionality, as mentioned in #22 

I would first start with making the 3 CV inputs and test a while around. The trigger CV is a low hanging fruit, so can also be done quickly.

**Comment by docb** [comment]
There is also a further condition: If the partial input 2-17 is connected then the all rnd triggers are ignored.
(this is also one reason why wonder if there is still a need for the rnd trigger)

**Comment by docb** [comment]
An example here:    https://vimeo.com/719448288

**Comment by docb** [comment]
Partially solved in 2,1.0. Open a new issue for things missing.
