### ISSUE TITLE
HexSeq timing issue

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#9]
Hi,

Using HexSeq I noted a strange behavior I'd suggest to correct.

Currently if I modify a sequence string (like '8888' in sequence window nr.2) and press Enter the module immediately sends the first trigger. Regardless about the position of the other sequences.

I propose that after saving a sequence-string-change the module shall wait for a reset input or the restart of the first sequence string before playing the recently saved sequence. Otherwise the sequences will be drifting forever.

Cheers, Andras

**Comment by docb** [comment]
yes this is a known issue, you may have to reset after changing the length of a sequence to restart all sequences. The feature behind is live coding. This is currently not well supported. If you don't change the length then it should work in the live scenario. However i have an idea to solve this.
thanks.

**Comment by firolightfog** [comment]
Thanks, Christian! I got it now! Not necessarily something to be solved.  I'll use it differently now. 

Although it's welcome if there's an easy way to provide an option. (Maybe a settings option in the context menu?)

**Comment by docb** [comment]
The current idea is: I would change the algorithm a bit, which would store a global song position instead of storing positions for each track. From the global song position it is possible to determine the current position of every track regardless if it is changed.
But this would make another feature impossible - to allow each track to be reset separately -  this could be also useful if one wants to have a single sequence reset in between the 4 bits.
So i'll think about ....

**Comment by firolightfog** [comment]
Timing issue was reviewed and related changes were implemented in v2.0.4
